// Generated by Rainfall.c on 2022.10.18 at 10.10.48.

#include <stddef.h>
#include <stdbool.h>

typedef char byte;
typedef size_t uxs;

int main(int argumentCount, char const* const* argumentArray) {
  int const decimal = (10);
  int const access = (decimal);
  int const group = (((access)));
  int const posate = (+(group));
  int negate = (-(posate));
  bool const not = (!(negate));
  int const complement = (~(not));
  int const multiply = ((not)*(complement));
  int const divide = ((complement)/(multiply));
  int const reminder = ((multiply)%(divide));
  int const add = ((divide)+(reminder));
  int const sub = ((reminder)-(add));
  int const leftShift = ((add)<<(sub));
  int const rightShift = ((sub)>>(leftShift));
  int const bitwiseAND = ((leftShift)&(rightShift));
  int const bitwiseXOR = ((rightShift)^(bitwiseAND));
  int const bitwiseOR = ((bitwiseAND)|(bitwiseXOR));
  bool const smallerThan = ((bitwiseXOR)<(bitwiseOR));
  bool const smallerOrEqual = ((bitwiseOR)<=(smallerThan));
  bool const largerThan = ((smallerThan)>(smallerOrEqual));
  bool const largerOrEqual = ((smallerOrEqual)>=(largerThan));
  bool const equal = ((largerThan)==(largerOrEqual));
  bool const notEqual = ((largerOrEqual)!=(equal));
  bool const logicalAND = ((equal)&&(notEqual));
  int logicalOR = ((notEqual)||(logicalAND));
}
