// Generated by Rainfall.c on 2022.10.18 at 12.02.40.

#include <stddef.h>
#include <stdbool.h>

typedef char byte;
typedef size_t uxs;

int main(int argumentCount, char const* const* argumentArray) {
}
